# Generated by Django 3.2.8 on 2022-04-06 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_gatepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='counsellor_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='hod_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='principal_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='section',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gatepass',
            name='year_coordinator_sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
