# Generated by Django 3.2.8 on 2022-05-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_user_is_warden'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='deny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
