# Generated by Django 3.2.8 on 2022-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20220505_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Check this if the user is super user(Administrator)', verbose_name='superuser status'),
        ),
    ]
